// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://texsltzecmvqprdjxtnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRleHNsdHplY212cXByZGp4dG5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTA0NTYsImV4cCI6MjA2OTQ4NjQ1Nn0.WNBXKASoTntVC7mF6yAoHc0_6UbMUp3Sv9NCm3AzCZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});